{% set name = "ligo-scald" %}
{% set version = "0.8.2" %}
{% set sha256 = "8a771030f203c582861f864a732fa00ea78b9aa4ea1419ffb060736b00451fa9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - scald = ligo.scald.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.7.1
    - pyyaml
    - bottle
    - python-dateutil
    - urllib3

test:
  imports:
    - ligo.scald
    - ligo.scald.deploy
    - ligo.scald.io
    - ligo.scald.mock
    - ligo.scald.serve
    - ligo.scald.utils

about:
  home: https://git.ligo.org/gstlal-visualisation/ligo-scald
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://docs.ligo.org/gstlal-visualisation/ligo-scald
  dev_url: https://git.ligo.org/gstlal-visualisation/ligo-scald
  summary: Gravitational-wave monitoring and data visualization tool

extra:
  recipe-maintainers:
    - myNameIsPatrick
