{% set name = "ligo-scald" %}
{% set version = "0.5.0" %}
{% set sha256 = "1ed9e352c151481a0e63d3226fd1cab7910d2a4844ad2b0cdc20923c4563be96" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - scald = ligo.scald.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - six
    - numpy >=1.7.1
    - scipy
    - h5py >=2.3.0
    - python-lal
    - pyyaml
    - bottle
    - ligo-common
    - ligo-segments
    - urllib3

test:
  imports:
    - ligo.scald
    - ligo.scald.aggregator
    - ligo.scald.deploy
    - ligo.scald.io
    - ligo.scald.mock
    - ligo.scald.serve
    - ligo.scald.utils

about:
  home: https://git.ligo.org/gstlal-visualisation/ligo-scald
  license: GPLv2+
  license_family: GPL
  license_file: LICENSE
  doc_url: https://docs.ligo.org/gstlal-visualisation/ligo-scald
  dev_url: https://git.ligo.org/gstlal-visualisation/ligo-scald
  summary: Gravitational-wave monitoring and data visualization tool

extra:
  recipe-maintainers:
    -  myNameIsPatrick
