{% set name = "ligo-scald" %}
{% set version = "0.8.5" %}
{% set sha256 = "12b606fc868a77181d1095b72689bf1849ca307f2c97a149784b7509b7ae211b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - scald = ligo.scald.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bottle
    - numpy >=1.7.1
    - python >={{ python_min }}
    - python-dateutil
    - pyyaml
    - setuptools
    - urllib3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ligo.scald
    - ligo.scald.deploy
    - ligo.scald.io
    - ligo.scald.mock
    - ligo.scald.serve
    - ligo.scald.utils
  commands:
    # check metadata
    - python -m pip check ligo-scald
    - python -m pip show ligo-scald
    # sanity-check entry points
    - scald --help

about:
  home: https://git.ligo.org/gstlal-visualisation/ligo-scald
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://docs.ligo.org/gstlal-visualisation/ligo-scald
  dev_url: https://git.ligo.org/gstlal-visualisation/ligo-scald
  summary: Gravitational-wave monitoring and data visualization tool

extra:
  recipe-maintainers:
    - duncanmmacleod
    - nothisisolivia
