travis:
  secure:
    BINSTAR_TOKEN: O1uiVvdiATDCvSNo0rLW0sqNrCyhMomJi+iIkxa1oqYv3LsAHWc1zc9CTCQWQV7y866jOlMbcbwllp04Anjeu9kuEjlH3coVfxqR7I38a0nezLpAxLsl1tdYvXSkz3G7jbMGBFzC4TOLxe+LbK5aGk1DMP0DxpicSvuYG8Z2N83+zF5IoVamwDJdE4V70jss8u3+SsNsW+b2H0HNhmxqXVl3Tg7QxqI9qqawDEy+nBGtcBUp4/XoQtD5lMqcrJc4M+mFggoXUjxBUp6nuf7iaV7wg5cb5e5tQmnayx7NmpUm1OUkhvfoPeCKJhhGHxgi/TQntB2WyAREayM+KL/CWArjRLniwU1G7ekAaf7ZI7rVVtHyG0FG2VG42w25VKhXeaUj4uBk0v+UrieGb9csSS30BhdI54vrU3SMBUAKRZ0c/8eigQYdRu5GoIMvX7xo84AGJnkDJKHEbUkHEDUX1a3WSO2d1e5STDjmRfotAVfWweg5+itgyA+FfugcdEy2bLrj8Vs99NuoWMM7L0TpBhIaO1XLFSdO+PLaN+E8qY7By479/FXY9gPgFAluEtYNi/SuFXAUTIkVAOQW4nr2DGWAiEwHSZnMXdjsOOm+MT9ydflVIDnpHaBXuxAWKo7ZQNXH8EGa5B8pA2k5Vq7GW33QaEA8opkDYOqZ+7ncL8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
